config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/no_search'

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  concern :votable do
    member do
      post 'create_vote'
      delete 'delete_vote'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable] do
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :comments, only: [:create], defaults: { commentable: 'question' }
    resources :answers, concerns: [:votable], except: [:index, :show, :edit], shallow: true do
      resources :comments, only: [:create], defaults: { commentable: 'answer' }
      patch :make_best, on: :member
    end
  end

  resources :comments, :only => [:create]

  resources :attachments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :member
  end

  resources :users, only: [:index, :show]

  get 'search', to: redirect('pages/no_search')
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Attachable
  
  has_many :answers, dependent: :destroy
  has_many  :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable 
  has_many :subscribe_lists, dependent: :destroy
  has_many :subscribers, class_name: 'User', through: :subscribe_lists
  belongs_to :user

  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true, length: { maximum: 1400 }
  validates :user, presence: true

  accepts_nested_attributes_for :attachments, reject_if: proc { |attrib| attrib['file'].nil? }, allow_destroy: true

  scope :created_yesterday, -> { where(created_at: Time.zone.now.yesterday.all_day) }

  after_create :subscribe_author

  self.per_page = 10

  def subscribe(user)
    self.subscribers << user unless has_subscribed? user
  end

  def unsubscribe(user)
    self.subscribers.delete(user) if has_subscribed? user
  end

  def has_subscribed?(user)
    subscribers.include? user
  end

  private

  def subscribe_author
    subscribe(user)
  end
end

app/controllers/api/v1/questions_controller.rb
class API::V1::QuestionsController < API::V1::BaseController
  skip_before_action :authenticate_user!, only: [:index, :show, :create]

  authorize_resource

  def index
    @questions= Question.all
    respond_with @questions, each_serializer: QuestionsListSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with @question = current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
  before_action :build_answer, only: :show
  # before_action :check_user, only: :destroy
  after_action  :publish_question, only: :create

  authorize_resource

  respond_to :js, only: :update

  include PublicIndex
  include Voted

  def index
    # respond_with(@questions = Question.all)
    respond_with(@questions = Question.paginate(page: params[:page]).order('created_at DESC'))
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  def subscribe
    @question.subscribe(current_user)
    redirect_to @question, notice: 'Subscribed successfully!'
  end

  def unsubscribe
    @question.unsubscribe(current_user)
    redirect_to @question, notice: 'Unsubscribed successfully!'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  # def check_user
  #   render text: 'You do not have permission to view this page.', status: 403 if @question.user_id != current_user.id
  # end

  def publish_question
    PrivatePub.publish_to("/questions", question: @question.to_json(include: :attachments)) if @question.valid?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
- cache @question do
  h1= @question.title
  hr
  .row
    .col-md-1
      = render 'votes/votes', resource: @question
    .col-md-5
      p= @question.body
.row
  .col-md-1
  .col-md-5
    p Attachments:
    ul
      - cache collection_cache_key_for :attachment do
        - @question.attachments.each do |a|
          div id="attachment_#{a.id}"
            li= link_to a.file.identifier, a.file.url
            - if can?(:destroy, a)
              = link_to 'Delete file', a, method: :delete, remote: true
    - if can?(:update, @question)
      = link_to 'Edit', '', class: 'edit-question-link btn btn-danger btn-xs', data: { question_id: @question.id }, remote: true
    - if can?(:destroy, @question)
      = link_to 'Delete question', question_path, method: :delete, class: 'button btn btn-danger btn-xs', style: "margin-left: 5px;"
    p
    - if user_signed_in?
      - if @question.has_subscribed?(current_user)
        = link_to 'Unsubscribe', unsubscribe_question_path(@question), method: :post
      - else
        = link_to 'Subscribe', subscribe_question_path(@question), method: :post
.row
  p
  - if can?(:update, @question)
    = bootstrap_form_for @question, remote: true, html: { id: "edit-question-#{@question.id}"} do |f|
      = f.text_field :title, label: 'Title'
      = f.text_area :body, label: 'Question'
      = f.submit 'Save'

app/views/questions/index.html.slim
.row
  .col-sm-12.col-md-8.col-md-offset-1.col-lg-8.col-lg-offset-1
    .questions
      - unless_empty @questions do
        - cache collection_cache_key_for :question do
          - @questions.each do |question|
            h3 = link_to question.title, question_path(question)
            = raw "Asked #{question.created_at.strftime '%d %B, %Y'} by #{question.user.email}"
            hr
    .row
      .col-md-offset-5.col-lg-offset-5
        = will_paginate @questions

- if current_user
  .user-auth data={ current_user: "#{ current_user.id }"}
= subscribe_to "/questions"

app/views/questions/new.html.slim
.row
  .col-sm-12.col-md-6.col-md-offset-3.col-lg-6.col-lg-offset-3
    = bootstrap_nested_form_for @question do |f|
      p
      = f.text_field :title, label: "Title"
      = f.text_area :body, label: "Text"
      p Attachments:
      p
        = f.fields_for :attachments, @question.attachments.build do |a|
          = a.file_field :file, label: "File"
          = a.link_to_remove "Clear", class: "btn btn-xs btn-default float_left"
        = f.link_to_add "Add more", :attachments, class: "btn btn-xs btn-default", style: "margin-left: 5px;"
      p= f.submit 'Create', class: "btn btn-primary"

app/views/questions/show.html.slim
.row
  .col-md-6.col-md-offset-3
    .question
      .question-error
      .comment-errors
      = render @question
    .row
      .col-md-4.col-md-offset-2
        = render 'comments/comments', resource: @question
        = render 'comments/form', resource: @question
    .row
      hr
      .answers data={ question_id: "#{@question.id}" }
        = render @question.answers
        .answer-errors
      - if can?(:create, @answer)
        .user-auth data={ current_user: "#{ current_user.id }"}
        = bootstrap_nested_form_for [@question, @answer], remote: true do |f|
          = f.text_area :body, label: 'Answer'
          = f.fields_for :attachments, @answer.attachments.build do |a|
            = a.file_field :file, label: "File"
            = a.link_to_remove "Clear", class: "btn btn-xs btn-default float_left"
          = f.link_to_add 'Add more', :attachments, class: "btn btn-xs btn-default", style: "margin-left: 5px;"
          p
          = f.submit 'Create', class: "btn btn-primary"
      - else
        | Sign in or sign up to leave answers

      = subscribe_to "/questions/#{@question.id}"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<div class="alert alert-danger"><%= j message %></div>');
  <% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
  $('.edit-question-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        question_id = $(this).data('questionId');
        $('form#edit-question-' + question_id).show();
  });
<% end %>