config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/no_search'

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  concern :votable do
    member do
      post 'create_vote'
      delete 'delete_vote'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable] do
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :comments, only: [:create], defaults: { commentable: 'question' }
    resources :answers, concerns: [:votable], except: [:index, :show, :edit], shallow: true do
      resources :comments, only: [:create], defaults: { commentable: 'answer' }
      patch :make_best, on: :member
    end
  end

  resources :comments, :only => [:create]

  resources :attachments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :member
  end

  resources :users, only: [:index, :show]

  get 'search', to: redirect('pages/no_search')
end

app/models/search.rb
class Search
  SEARCH_OPTIONS = %w(Questions Answers Comments Users)

  def self.filter(query, options = {})
    condition = options[:condition]
    safe_query = Riddle::Query.escape(query)

    if SEARCH_OPTIONS.include?(condition)
      condition.singularize.constantize.search(safe_query)
    else
      ThinkingSphinx.search safe_query
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!
  authorize_resource

  def search
    if params[:query].present?
      @results = Search.filter(params[:query], condition: params[:condition])
    else
      @results = []
    end
    respond_with @results
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_answer.html.slim
div = truncate(answer.body, length: 200)

app/views/search/_comment.html.slim
div = truncate(comment.body, length: 200)

app/views/search/_form.html.slim
/ .row
/   .col-sm-12.col-md-10.col-md-offset-1.col-lg-10.col-lg-offset-1
= form_tag search_path, method: 'get', class: 'navbar-form navbar-left'
  .form-group.input-group-sm
    = text_field_tag :query, params[:query], class: 'form-control'

  .form-group.input-group-sm
    = select_tag(:condition,
        options_for_select(Search::SEARCH_OPTIONS, params[:condition]), prompt: 'Everywhere', class: 'form-control')

  = submit_tag 'Search', name: nil, class: 'btn btn-default btn-sm'

app/views/search/_question.html.slim
div
  p= link_to question.title, question_path(question)

app/views/search/_user.html.slim
div = user.email

app/views/search/search.html.slim
h4 Search results

.banner
  | Search is disabled, because no free sphinx on Heroku.

.results
  - if @results.any?
      - @results.each do |result|
        = render partial: "#{result.class.name.downcase}", object: result