config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/no_search'

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  concern :votable do
    member do
      post 'create_vote'
      delete 'delete_vote'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable] do
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :comments, only: [:create], defaults: { commentable: 'question' }
    resources :answers, concerns: [:votable], except: [:index, :show, :edit], shallow: true do
      resources :comments, only: [:create], defaults: { commentable: 'answer' }
      patch :make_best, on: :member
    end
  end

  resources :comments, :only => [:create]

  resources :attachments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :member
  end

  resources :users, only: [:index, :show]

  get 'search', to: redirect('pages/no_search')
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Attachable
  include Votable

  belongs_to :question, touch: true
  belongs_to :user

  has_many  :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, length: { maximum: 1400 }
  validates :user, presence: true

  default_scope { order(best: :desc).order(created_at: :asc) }

  after_create :report_subscribers

  def make_best
    question.answers.update_all(best: false)
    update(best: true)
  end

  private

  def report_subscribers
    ReportSubscribersJob.perform_later(self)
    # self.question.subscribers.find_each do |subscriber|
    #   ReportMailer.delay.report(subscriber, self)
    # end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :load_answer, only: [:edit, :update, :destroy, :make_best, :render_answer, :render_error, :show]
  before_action :load_question, only: [:create, :make_best, :update]
  before_action :answer_owner, only: [:update, :destroy]
  before_action :question_owner, only: :make_best
  after_action  :publish_answer, only: :create
  # after_action  :increase_user_rating, only: :create

  authorize_resource

  respond_to :js, only: [:destroy, :make_best, :create, :update]

  include PublicIndex
  include Voted

  def create
    respond_with(@answer = @question.answers.create(answer_params))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def make_best
    respond_with(@answer.make_best)
  end

  private

  def load_question
    @question = if params.key?(:question_id)
                  Question.find(params[:question_id])
    else
      @answer.question
    end
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    answer_params = params.require(:answer).permit(:body, :user_id, attachments_attributes: [:id, :file, :_destroy])
    answer_params.merge(user_id: current_user.id)
  end

  def answer_owner
    render text: 'You do not have permission to view this page.', status: 403 if @answer.user_id != current_user.id
  end

  def question_owner
    render text: 'You do not have permission to view this page.', status: 403 if @question.user_id != current_user.id
  end

  def publish_answer
    PrivatePub.publish_to("/questions/#{@question.id}", answer: @answer.to_json(include: :attachments), author: @answer.user_id) if @answer.valid?
  end

  # def increase_user_rating
  #   tmp_rating = Rating.find_or_create_by(user_id: @answer.user, r_type: "answer")
  #   tmp_rating.count += 1
  #   tmp_rating.save!f
  # end
end

app/controllers/api/v1/answers_controller.rb
class API::V1::AnswersController < API::V1::BaseController
  skip_before_action :authenticate_user!, only: [:index, :show, :create]
  before_action :find_question, except: :show

  authorize_resource

  def index
    respond_with @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user_id: current_resource_owner.id))
    respond_with @answer
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
/ - cache answer do
- if answer.persisted?
    div id=("answer_#{ answer.id }")
      - if answer.best
        | This is best answer
      p = answer.body
      = render 'comments/comments', resource: answer
      = render 'comments/form', resource: answer
      = render 'votes/votes', resource: answer
      - if answer.attachments.exists?
        p Attachments:
        ul
          - cache collection_cache_key_for :attachment do
            - answer.attachments.each do |a|
              div id="attachment_#{a.id}"
                li= link_to a.file.identifier, a.file.url
                - if can?(:destroy, a)
                  = link_to 'Delete file', a, method: :delete, remote: true
      - if can?(:update, answer)
        = link_to 'Edit', '', class: 'edit-answer-link btn btn-primary btn-xs', data: { answer_id: answer.id }
        = bootstrap_form_for [answer], remote: true, html: { id: "edit-answer-#{ answer.id }"} do |f|
          = f.text_area :body, label: 'Edit answer'
          = f.submit 'Save'
      - if can?(:destroy, answer)
        = link_to 'Delete answer', [answer], class: 'btn btn-danger btn-xs', remote: true, method: :delete
      - if can?(:make_best, answer)
        = link_to 'Best answer', make_best_answer_path(answer), class: 'btn btn-success btn-xs', method: :patch, remote: true

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<div class="alert alert-danger"><%= j message %></div>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
  });
  $('.new_answer').find('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<div class="alert alert-danger"><%= j message %></div>');
  <% end %>
<% else %>
  $('#answer_<%= @answer.id %>').remove();
<% end %>

app/views/answers/make_best.js.erb
$('.answers').html('<%= j render @question.answers %>');
$('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
});

app/views/answers/new.html.slim
= form_for [@answer.question, @answer] do |f|
  = f.label :body, 'Answer'
  = f.text_area :body
  = f.submit 'Create'

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<div class="alert alert-danger"><%= j message %></div>');
  <% end %>
<% else %>
  $('#answer_<%= @answer.id %>').html('<%= j render @answer %>');
  $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
  });
<% end %>