config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/no_search'

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  concern :votable do
    member do
      post 'create_vote'
      delete 'delete_vote'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :questions, concerns: [:votable] do
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :comments, only: [:create], defaults: { commentable: 'question' }
    resources :answers, concerns: [:votable], except: [:index, :show, :edit], shallow: true do
      resources :comments, only: [:create], defaults: { commentable: 'answer' }
      patch :make_best, on: :member
    end
  end

  resources :comments, :only => [:create]

  resources :attachments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :member
  end

  resources :users, only: [:index, :show]

  get 'search', to: redirect('pages/no_search')
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
    can :read, :all
    can :search, :all 
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :manage, :profile
    can :create, [Question, Answer, Comment]
    can :update, [Question, Answer], user: user

    can :destroy, [Question, Answer, Comment], user: user
    can :destroy, Attachment do |attachment|
      attachment.attachable.user_id == user.id
    end

    can :make_best, Answer do |answer|
      answer.question.user_id == user.id
    end

    can :create_vote, [Answer, Question] do |resource|
      user.id != resource.user_id && !resource.voted_by?(user)
    end

    can :delete_vote, [Answer, Question] do |resource|
      user.id != resource.user_id
    end

    can :subscribe, Question
    can :unsubscribe, Question
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Attachable
  include Votable

  belongs_to :question, touch: true
  belongs_to :user

  has_many  :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, length: { maximum: 1400 }
  validates :user, presence: true

  default_scope { order(best: :desc).order(created_at: :asc) }

  after_create :report_subscribers

  def make_best
    question.answers.update_all(best: false)
    update(best: true)
  end

  private

  def report_subscribers
    ReportSubscribersJob.perform_later(self)
    # self.question.subscribers.find_each do |subscriber|
    #   ReportMailer.delay.report(subscriber, self)
    # end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true, touch: true

  mount_uploader :file, FileUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, :user_id, :commentable_id, :commentable_type, presence: true
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Attachable
  
  has_many :answers, dependent: :destroy
  has_many  :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable 
  has_many :subscribe_lists, dependent: :destroy
  has_many :subscribers, class_name: 'User', through: :subscribe_lists
  belongs_to :user

  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true, length: { maximum: 1400 }
  validates :user, presence: true

  accepts_nested_attributes_for :attachments, reject_if: proc { |attrib| attrib['file'].nil? }, allow_destroy: true

  scope :created_yesterday, -> { where(created_at: Time.zone.now.yesterday.all_day) }

  after_create :subscribe_author

  self.per_page = 10

  def subscribe(user)
    self.subscribers << user unless has_subscribed? user
  end

  def unsubscribe(user)
    self.subscribers.delete(user) if has_subscribed? user
  end

  def has_subscribed?(user)
    subscribers.include? user
  end

  private

  def subscribe_author
    subscribe(user)
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user

end

app/models/search.rb
class Search
  SEARCH_OPTIONS = %w(Questions Answers Comments Users)

  def self.filter(query, options = {})
    condition = options[:condition]
    safe_query = Riddle::Query.escape(query)

    if SEARCH_OPTIONS.include?(condition)
      condition.singularize.constantize.search(safe_query)
    else
      ThinkingSphinx.search safe_query
    end
  end
end

app/models/subscribe_list.rb
class SubscribeList < ActiveRecord::Base
  belongs_to :subscriber, class_name: 'User', foreign_key: 'user_id'
  belongs_to :subscription, class_name: 'Question', foreign_key: 'question_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook, :twitter]
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :identitys, dependent: :destroy
  has_many :subscribe_lists, dependent: :destroy
  has_many :subscriptions, class_name: 'Question', through: :subscribe_lists

  scope :all_except, ->(user) { where.not(id: user) }

  attr_accessor :without_password

  def password_required?
    super && !without_password
  end

  def self.find_for_oauth(auth)
    identity = Identity.includes(:user).find_or_create_by(uid: auth.uid, provider: auth.provider)
    return identity.user if identity.user.present?

    if auth.info.email.present?
      user = User.find_by(email: auth.info.email)
      unless user.present?
        user = User.new(email: auth.info.email)
        user.without_password = true
        user.save!
      end
      identity.update!(user: user)
      return user
    end

    user = User.new
    user.identitys << identity
    user
  end

  def self.send_daily_digest
    find_each.each do |user|
      DailyMailer.delay.digest(user)
    end
  end

  # def self.all_rating
  #   rating = Rating.where(user_id: :user).sum
  #   user_rating = User.find(id: :user)
  #   user_rating = rating
  #   user_rating.save!
  # end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :user, presence: true, uniqueness: { scope: [:votable_id, :votable_type] }
  validates :value, inclusion: [-1, 1]
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_authorization_check
  
  def about
  end

  def no_search
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    page = params[:page]
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}-#{page}"
  end

  def unless_empty(collection, message = "No questions ", &block)
    if collection.empty?
      # concat(message)
      concat(render 'layouts/no_questions')
    else
      concat(capture(&block))
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def markdown(source)
    Kramdown::Document.new(source, {coderay_css: :class, coderay_line_numbers: nil}).to_html.html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.slim
.row
  .col-sm-12.col-md-10.col-md-offset-1.col-lg-10.col-lg-offset-1
    - if flash[:notice]
      div class="alert alert-success"
        = notice
    - if flash[:alert]
      div class="alert alert-danger"
        = alert

app/views/layouts/_header.html.slim
header
  .navbar-inverse.navbar-default.navbar-static-top
    .container-fluid
      .col-sm-12.col-md-10.col-md-offset-1.col-lg-10.col-lg-offset-1
        .navbar-header
          button.navbar-toggle data-target="#navbar-ex-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/"
            span Q&A point
          = render partial: 'search/form'
        #navbar-ex-collapse.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li class="navbar-text" = current_user.email
              li = button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'button btn btn-primary navbar-btn btn-sm'
            - else
              li = button_to 'Sign in', new_user_session_path, class: 'button btn btn-primary navbar-btn'

app/views/layouts/_menu.html.slim
.row
  .col-sm-12.col-md-10.col-md-offset-1.col-lg-10.col-lg-offset-1
    = button_to 'Tags', questions_path, method: :get, class: 'button btn-sm btn btn-warning navbar-btn pull-right'
    = button_to 'Users', users_path, method: :get, class: 'button btn-sm btn btn-warning navbar-btn pull-right'
    = button_to 'Badges', questions_path, method: :get, class: 'button btn-sm btn btn-warning navbar-btn pull-right'
    = button_to 'FAQ', pages_about_path, method: :get, class: 'button btn-sm btn btn-warning navbar-btn pull-right'
    - if can?(:create, Question)
      = button_to 'Ask question', new_question_path, method: :get, class: 'button btn btn-sm btn-warning navbar-btn pull-right'

app/views/layouts/_no_questions.html.slim
h1 На данный момент вопросов нет
p Если вы хотите побольше узнать о приложении обратитесь к странице #{link_to 'FAQ', pages_about_path, method: :get}
/= markdown("")

app/views/layouts/application.html.slim
doctype html
head
  title Q&A point
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false
  = javascript_include_tag 'application', 'data-turbolinks-track' => false
  = csrf_meta_tags
body
  = render 'layouts/header'
  .section
    .container-fluid
      = render partial: 'layouts/menu'
      = render partial: 'layouts/alert'
      = yield

app/views/pages/about.html.slim
.row
  .col-sm-12.col-md-8.col-md-offset-1.col-lg-8.col-lg-offset-1
    - cache('faq_about_page') do
      h1 FAQ
      p На этой странице я постарался ответить на все вопросы, которые могут возникнуть у человека, который впервые открыл данный сайт, так она одновременно и FAQ и about.

      h2 Зачем?
      p Проект был написан на курсах профессиональной разработки от школы Thinknetica.com, в качестве учебного, чтобы отработать основные приемы грамотной разработки веб-приложений на Ruby on Rails.
      h2 Функционал
      p Функционал проекта скопирован с сайта stackoverflow, который является сервисом вопросов и ответов. Таким образом, основные фнукции, доступные зарегистрированным пользователям, это создание вопросов и ответов.
      h2 Что используется?
      p В проекте используется множество различных технологий помимо Rails, как мне кажется, легче всего описать это через разбор гем-файла (Gemfile).
      = markdown("~~~ruby\ngem 'rails', '~> 4.2'\ngem 'sass-rails', '~> 5.0'\ngem 'uglifier', '>= 1.3.0'\ngem 'coffee-rails', '~> 4.1.0'v\ngem 'jquery-rails'\ngem 'turbolinks'\ngem 'jbuilder', '~> 2.0'\n~~~")
      p На момент разработки наиболее актуальная версия рельс.
      = markdown("~~~ruby\ngem 'pg'\n~~~")
      p Дефакто в Rails разработке, пока не знаю postgres на таком же уровне как и mysql, но верю что он сделает мир лучше.
      = markdown("~~~ruby\ngem 'slim-rails'\n~~~")
      p Использование slim вместо erb позволяет значительно упростить написание view и облегчить чтение кода. (И в нем нету ужасных %-ов).
      = markdown("~~~ruby\ngem 'devise'\n~~~")
      p По книге Майкла Хартла я уже научился реализовывать аутентификацию в Rails, но зачастую нет необходимости писать это самостоятельно, devise мощный инструмент созданный специально для этого.
      = markdown("~~~ruby\ngem 'bootstrap-sass', '3.2.0.0'\n~~~")
      p Очень люблю этот фреймворк, облегчает программистам задачу создания красивых интерфейсов.
      = markdown("~~~ruby\ngem 'bootstrap_form'\n~~~")
      p Позволяет проще создавать формы с bootstrap оформлением.
      = markdown("~~~ruby\ngem 'carrierwave'\n~~~")
      p При создании вопроса или ответа пользователь может загрузить файл, который доступен по ссылке, carrierwave нужен для этого.
      = markdown("~~~ruby\ngem 'remotipart'\n~~~")
      p Так же используется для загрузки файлов, чтобы формы работали через AJAX.
      = markdown("~~~ruby\ngem 'nested_form'\n~~~")
      p Мульти-модельные формы.
      = markdown("~~~ruby\ngem 'handlebars_assets'\n~~~")
      p Шаблонизатор handlebars применяется при вставке новых вопросов и ответов на страницу через AJAX.
      = markdown("~~~ruby\ngem 'private_pub'\n~~~")
      p Это реализация вебсокетов для rails (обертка поверх faye), позволяет легко создавать каналы и отсылать в них данных. Таким образом, если у пользователя открыт вопрос, при добавлении нового ответа он тут же появляется на странице, без перезагрузки самой страницы.
      = markdown("~~~ruby\ngem 'thin'\n~~~")
      p Зависимость private_pub, больше нигде не используется.
      = markdown("~~~ruby\ngem 'responders', '~> 2.0'\n~~~")
      p Упрощаем себе жизнь и написание контроллеров, которые, при этом, становятся легче.
      = markdown("~~~ruby\ngem 'omniauth'\ngem 'omniauth-facebook'\ngem 'omniauth-twitter'\n~~~")
      p В приложении пользователь может зарегистрироваться/авторизоваться через социальные сети, в частности facebook и twitter.
      = markdown("~~~ruby\ngem 'cancancan'\n~~~")
      p Разграничиваем права пользователей, на данный момент реализованы: гость, пользователь и администратор.
      = markdown("~~~ruby\ngem 'doorkeeper'\n~~~")
      p Так как в проекте есть API, используется doorkeeper в качестве OAuth провайдера.
      = markdown("~~~ruby\ngem 'active_model_serializers'\n~~~")
      p Сериализуем объекты в JSON.
      = markdown("~~~ruby\ngem 'oj'\ngem 'oj_mimic_json'\n~~~")
      p Ускоряем парсинг JSON.
      = markdown("~~~ruby\ngem 'sidekiq'\n~~~")
      p Крутая штука для отложенных задач, в частности здесь используется для отправки писем/рассылок.
      = markdown("~~~ruby\ngem 'whenever'\n~~~")
      p Управляем задачами Cron из рельсового приложения. Например через него задается запуск рассылки еженедельного дайджеста и переиндексация поиска.
      = markdown("~~~ruby\ngem 'mysql2', '~> 0.3.18'\ngem 'thinking-sphinx', '~> 3.1.4'\n~~~")
      p А вот и сам полнотекстовый поиск.
      = markdown("~~~ruby\ngem 'dotenv'\ngem 'dotenv-deployment', require: 'dotenv/deployment'\n~~~")
      p Нужен для деплоя, причем второй гем deprecated, но ни как не дойдут руки переделать.
      = markdown("~~~ruby\ngem 'therubyracer'\n~~~")
      p Embed the V8 JavaScript interpreter into Ruby. А зачем он в проекте нужен не помню, может просто добавил чтобы был?
      = markdown("~~~ruby\ngem 'unicorn'\n~~~")
      p Хороший веб-сервер для Rails и хотя Puma мне нравится больше, пока проект работает на единороге.
      = markdown("~~~ruby\ngem 'redis-rails'\n~~~")
      p Используем redis для russian doll caching и для sidekiq
      = markdown("~~~ruby\ngem 'will_paginate'\ngem 'bootstrap-will_paginate'\n~~~")
      p Добавил уже после курсов, собственно пагинация на главной.
      = markdown("~~~ruby\ngem 'kramdown'\ngem 'coderay'\n~~~")
      p Добавил только что, чтобы сделать подсветку синтаксиса.
      = markdown("~~~ruby\ngroup :development do\n  gem 'capistrano', require: false\n  gem 'capistrano-bundler', require: false\n  gem 'capistrano-rails', require: false\n  gem 'capistrano-rvm', require: false\n  gem 'capistrano-sidekiq', require: false\n  gem 'capistrano3-unicorn', require: false\nend\n~~~")
      p Деплой приложения через Capistrano
      = markdown("~~~ruby\ngroup :development, :test do\n  gem 'byebug'\n  gem 'web-console', '~> 2.0'\n  gem 'spring'\n~~~")
      p Ну и заканчивается гемфайл группой дев/тест. Первые три гема ставятся с Rails.
      = markdown("~~~ruby\n  gem 'rspec-rails'\n~~~")
      p Тестируем с помощью rspec (Unit-тесты).
      = markdown("~~~ruby\n  gem 'factory_girl_rails'\n~~~")
      p Генерим данные с помощью фабрик, это удобнее чем фикстуры.
      = markdown("~~~ruby\n  gem 'shoulda-matchers'\n~~~")
      p Упрощаем написание тестов.
      = markdown("~~~ruby\n  gem 'capybara'\n~~~")
      p Тестируем с помощью capybara (Интеграционные тесты).
      = markdown("~~~ruby\n  gem 'launchy'\n~~~")
      p Используется для запуска бразуера когда вызывается <code>save_and_open_page</code> в тестах.
      = markdown("~~~ruby\n  gem 'pry'\n  gem 'pry-rails'\n~~~")
      p Дебажим через <code>binding.pry</code>.
      = markdown("~~~ruby\n  gem 'capybara-webkit'\n~~~")
      p Чтобы тестировать javascript но не запускать сам браузер, используем этот драйвер.
      = markdown("~~~ruby\n  gem 'database_cleaner'\n~~~")
      p Не засоряем базу данных во время тестов.
      = markdown("~~~ruby\n  gem 'letter_opener'\n~~~")
      p Проверяем отправку писем.
      = markdown("~~~ruby\n  gem 'capybara-email'\n~~~")
      p Тестируем отправку писем.
      = markdown("~~~ruby\n  gem 'json_spec'\n~~~")
      p В API данные "бегают" по JSON, поэтому его надо тестировать.
      h2 Прогресс
      p Все что сделано по проекту, а так же то, что у меня в планах я стараюсь отражать в <a href="https://github.com/tonymadbrain/qna/issues" target="_blank">github issues</a>. Каждая тема разрабатывалась в отдельной ветке и мерджилась в мастер через пулл-реквест. Сейчас, когда некому проводить кодревью, я не испольльзую PR, и часто могу коммитить прямо в мастер :).

app/views/pages/no_search.html.slim
h4 Search disabled

.banner
  | Search is disabled, due no free sphinx on Heroku.